title: Docs
description: The extensive documentation for contributing to the CSArtisan post repository.
remote_theme: pmarsceill/just-the-docs
# theme: just-the-docs

favicon_ico: "/assets/favicon.ico"

url: https://docs.csartisan.org/
baseurl: 
logo: "assets/img/logo.png"

aux_links:
  Production: https://csartisan.org
  Github: https://github.com/csartisan

color_scheme: dark

# Contacts
# Phone links cannot contain spaces or dashes. Ex. 1234567890, NOT (123)-456-7890.
techcontact: 6267108965
manager: 
editor:
advisor: 

callouts:
  danger:
    title: Warning!
    color: red
  developers:
    title: Contributors
    color: blue
  important:
    title: 
    color: yellow
  tip:
    title: Tip 💡 
    color: yellow
  next:
    title: 
    color: green
  report:
    title:
    color: red